repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending

-   repo: local
    hooks:
    -   id: check-launch-file-names
        name: Check ROS 2 launch file names
        entry: .pre-commit/check_launch_file_names.py
        language: python
        types: [file]
