name: Test Template

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Print Hello World
              run: echo "Hello, World!"
