name: ROS CI Test Build

on:
  push:
    branches: [main, devel]
    paths-ignore:
      - '.clang-format'
      - '.docker/**'
      - '.github/workflows/add-opened-issue-to-project.yml'
      - '.github/workflows/notify-unlabeled-issue.yml'
      - '.github/workflows/pre-commit.yml'
      - '.gitignore'
      - '.codex/**'
      - 'AGENTS.md'
      - '.pre-commit-config.yaml'
      - '.pre-commit/**'
      - 'LICENSE'
      - 'README.md'
      - '**/*.md'
      - 'change_name.py'
      - 'commit.sh'
      - 'pyproject.toml'
      - 'yammlint.yml'
  pull_request:
    branches: [main, devel]
    paths-ignore:
      - '.clang-format'
      - '.docker/**'
      - '.github/workflows/add-opened-issue-to-project.yml'
      - '.github/workflows/notify-unlabeled-issue.yml'
      - '.github/workflows/pre-commit.yml'
      - '.gitignore'
      - '.codex/**'
      - 'AGENTS.md'
      - '.pre-commit-config.yaml'
      - '.pre-commit/**'
      - 'LICENSE'
      - 'README.md'
      - '**/*.md'
      - 'change_name.py'
      - 'commit.sh'
      - 'pyproject.toml'
      - 'yammlint.yml'
  workflow_dispatch:

jobs:
  build:
    name: ROS CI Test Build
    uses: Real-Move/realmove-actions/.github/workflows/reusable-ros-ci.yml@main
    with:
      ros_distro: humble
      workspace_mode: deps
      skip_tests: false
      skip_rosdep_install: false
      rosdep_check: false
    secrets:
      REPO_ORG_PAT: ${{ secrets.REPO_ORG_PAT }}
