name: Sync pre-commit config

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - ".pre-commit-config.local.yaml"

jobs:
  sync:
    uses: Real-Move/realmove-actions/.github/workflows/reusable-sync-pre-commit.yml@main

    permissions:
      contents: write
      pull-requests: write
